<?php


function stuff_block_info() {

    $blocks['pauer_copyright'] = array(
        'info' => t('Copyright'),
    );
    return $blocks;
}

function stuff_block_view($delta = '') {
    $block="";
    switch ($delta) {
        case 'pauer_copyright':
            $version=system_get_info('module');
            if ($version) {
                $version=$version['pauer']['version'];
            }
            $block['content'] = t('Copyright @year. All rights reserved. Version: '.$version, array('@year' => date("Y")));
            break;

    }
    return $block;
}