<?php

// Plugin definition
$plugin = array(
  'title' => t('Pauer 2-1-2'),
  'category' => t('Pauer'),
  'icon' => 'pauer212.png',
  'theme' => 'pauer_212',
  'css' => '212.css',
  'regions' => array(
    'left_side' => t('Content Left side'),
    'right_side' => t('Content Right side'),
    'bottom' => t('Content Bottom'),
    'bottom_left_side' => t('Bottom Left side'),
    'bottom_right_side' => t('Bottom Right side'),
    'title' => t('Title'),
  ),
);
